### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by szabo-roland** [fsahin/graph-drawer#1]
Hi!
Sorry about my bad English. 
I just found your work here, and i like to use it in one of my project.
As you maybe know, projects without license text qualify as a copyrighted license, which does not provide freedom to modify and redistribute.
By the way, my project will be part of a bachelor's thesis.
So i ask you with respect, to put some license text into your repository. 
If you will not provide license, just close this issue, so i will know, and i will search another base project.

Have a nice day, sincerely Roland.

**Comment by fsahin** [comment]
I added an MIT license file. You can use it however you like :) Good luck on your thesis.

**Comment by szabo-roland** [comment]
Thanks! :)
